// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadEpubFile() {
  return window['go']['main']['App']['LoadEpubFile']();
}

export function NextFile() {
  return window['go']['main']['App']['NextFile']();
}

export function PrevFile() {
  return window['go']['main']['App']['PrevFile']();
}

export function UpdatePage() {
  return window['go']['main']['App']['UpdatePage']();
}
