// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {regexp} from '../models';

export function CssRegex():Promise<regexp.Regexp>;

export function HtmlRegex():Promise<regexp.Regexp>;

export function ImageRegex():Promise<regexp.Regexp>;

export function LoadEpubFile():Promise<void>;

export function NextFile():Promise<void>;

export function PrevFile():Promise<void>;

export function UpdatePage():Promise<void>;
