// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadEpubFile():Promise<void>;

export function NextFile():Promise<void>;

export function PrevFile():Promise<void>;

export function UpdatePage():Promise<void>;
